name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'
  push:
    branches:
      - dev
      - master
    paths-ignore:
      - 'README.md'
      - 'doc/**'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout branch "${{ github.ref_name }}"
        run: |
          git clone --no-checkout https://github.com/pinamahn/tubular.git .
          git config core.symlinks false
          git checkout --progress --force ${{ github.ref_name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: 'gradle'

      - name: Build debug APK
        run: |
          curl ipinfo.io
          ./gradlew assembleDebug
          find . -iname "*apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk
